# Generated by Django 3.0.6 on 2020-06-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newspost',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('content', models.CharField(default='', max_length=5000)),
                ('slug1', models.CharField(default='', max_length=400)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='news/images')),
            ],
        ),
    ]
