# Generated by Django 3.0.6 on 2020-07-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='content',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
