# Generated by Django 3.0.6 on 2020-06-15 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('writer', models.CharField(default='', max_length=50)),
                ('content1', models.TextField(blank=True, default='', max_length=5000)),
                ('pub_date', models.DateTimeField()),
                ('slug', models.CharField(default='', max_length=200)),
                ('thumbnail', models.ImageField(blank=True, default='', upload_to='media/images')),
                ('thumbnail1', models.ImageField(blank=True, default='', upload_to='media/images')),
                ('thumbnail2', models.ImageField(blank=True, default='', upload_to='media/images')),
            ],
        ),
        migrations.CreateModel(
            name='Blogcomment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=100)),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Blogcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
